openapi: 3.0.3
info:
  title: Example Context Serverless
  description: API documentation to interact with Example Context service.
  version: 1.0.0
servers:
  -
    url: http://localhost:3000
    description: Local development server.
security:
  - accessToken: []
paths:
  /example-modules/{id}:
    $ref: ../../../../../docs/example-context/example-module/path.yml
  /api/version:
    $ref: ../../../../../docs/example-context/api/version.yml
components:
  securitySchemes:
    accessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ExampleModule:
      $ref: ../../../../../docs/example-context/example-module/example-module.yml#/ExampleModule