name: Tests
on:
  push:
    branches:    
      - 'master'
  pull_request:
    paths-ignore:
      - "**.md"
env:
  # Dummy values so aws clients don´t complain (integration tests are using a dockerized local dynamodb)
  AWS_ACCESS_KEY_ID: key
  AWS_SECRET_ACCESS_KEY: secret
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --tags origin
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: make test_gh